version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: root
  MYSQL_PASSWORD: kunaguero10
  MYSQL_DATABASE: pcus
  REACT_APP_SERVER_PORT: 8000

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: kunaguero10
    ports:
      - 3307:3306
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  server:
    build: ./
    depends_on:
      - mysql
    expose:
      - 8000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      # - /server/app/node_modules
    links:
      - mysql
    command: npm run dev
volumes:
    db:
#   client:
#     build: ./client
#     environment:
#       <<: *common-variables
#       NODE_PATH: src
#     expose:
#       - 3000
#     ports:
#       - 3000:3000
#     volumes:
#       - ./client/src:/app/src
#     links:
#       - server
#     command: npm start